### PR TITLE
fix(sessionStorage): proper detect sessionStorage

### PR DESCRIPTION
**Pull request by jercoh**

### CODE REVIEW

**Comment by jercoh** [comment]
#30

**Comment by mgonto** [comment]
Looks great.

Merging!

Thanks!!!

**Comment by jercoh** [comment]
Thanks!!

**Comment by jercoh** [comment]
Can you please update the dist folder to get the latest version with Bower?
Thanks!

**Comment by mgonto** [comment]
Updated

**Comment by jercoh** [comment]
Thank you!

**Pull request merged**
