### PR TITLE
fix private browsing and cordova

### PR DESCRIPTION
**Pull request by gimox**
- fix private browsing
- cordova/ionic fix
- exec test for storage only one time (=performance)

### CODE REVIEW

**Comment by mgonto** [comment]
Hey thanks for the PR!

Just one question, why using numbers for `localStorageType` instead of a boolean? Just change this to a boolean and I'll merge.

Thanks!

**Comment by mgonto** [comment]
Also, besides calling the `set` you should check as well that `localStorage` does exist. So you should do both checks.

**Comment by gimox** [comment]
I use number because in a near feature can be more than two methods for storing data.
Now we have cookes and localstorage but there are: indexddb and sqllite engine (see pouchdb) that can be implemented.

**Comment by mgonto** [comment]
@gimox that makes complete sense.

I'd still use boolean for now, and as soon as we start using more, I'd change it to number. Would that make sense?

Thanks again for the PR :).

**Comment by gimox** [comment]
Yes it right. So now i have a private fork with pouchdb implemented that work good, say me if can be interesting and i push it to public repo.

**Comment by mgonto** [comment]
We're interested on it.

However, Let's first merge this PR with the boolean.

Then, let's submit another one for pouchdb. Would that make sense?

That way the PRs are more atomic :).

Thanks!

**Comment by gimox** [comment]
ok. thanks.

**Comment by ozooner** [comment]
Hi, what's the status on this?

**Comment by gimox** [comment]
too slow...man too slow...

**Pull request closed without merging**
