### PR TITLE
Change store service to a provider

### PR DESCRIPTION
**Pull request by 4kochi**
* add `sessionStorage` store
* change store with `storeProvider.setStore()` or set it in `store.getNamespacedStore()`
* add lint task for jshint checks `gulp lint`
* add code coverage task `gulp cover`

### CODE REVIEW

**Comment by 4kochi** [comment]
🔔 @mgonto 😉

**Comment by mgonto** [comment]
Hey sorry bout the delay. It looks awesome :).

Just 2 questions:
* The Karma ALL is only testing it with `PhantomJS`. Is that the intention? What's the difference with the one that was already there?
* Why did you do the coverage as a different Karma config instead of just adding the coverage to the existing test runner?

Thanks again for the PR!

**Comment by 4kochi** [comment]
Did you run the gulp test-all task? It should use all browser found on your system. The plugin `karma-detect-browsers` overwrites the browsers array in karma. 

I can try to merge the normal karma config and the karma coverage config together.

**Comment by 4kochi** [comment]
I removed the extra karma file for code coverage. Also you should consider adding travis so that all test run a each push/pull request to the repo. Just nice to have :sunglasses:

**Comment by mgonto** [comment]
Now it looks awesome :).

Thanks for the update :).

Merging. I'll add Travis and release it later this week :).

Thanks for all the hard work!

**Pull request merged**
